"""
PSI-based drift detection for the Car Valuation API.

Population Stability Index (PSI) measures how much a distribution has
shifted between a reference (training) population and a current population.

Industry thresholds:
    PSI < 0.10  → No significant shift. Model is stable.
    0.10–0.20   → Moderate shift. Monitor closely.
    PSI > 0.20  → Significant shift. Investigate and consider retraining.

Formula:
    PSI = Σ (actual_% − expected_%) × ln(actual_% / expected_%)

where the sum is over bins of the feature distribution.

References:
    Siddiqi (2006) — Credit Risk Scorecards.
    Yurdakul (2018) — Statistical Properties of PSI.
"""

import json
import logging
import os
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)

_BASELINE_PATH_ENV = "BASELINE_PATH"
_BASELINE_PATH_DEFAULT = "data/baselines/training_baseline.json"
_CLOUDWATCH_NAMESPACE = "CarValuation"

# Features monitored for drift
_MONITORED_FEATURES = ["mileage", "engine_power", "car_age_years", "luxury_tier"]

_PSI_THRESHOLDS = {
    "stable": 0.10,
    "monitor": 0.20,
}


def compute_psi(expected: np.ndarray, actual: np.ndarray, bin_edges: np.ndarray) -> float:
    """
    Compute Population Stability Index between two distributions.

    Args:
        expected:  1D array of values from the reference (training) population.
        actual:    1D array of values from the current (production) population.
        bin_edges: Pre-computed bin edges from the training distribution.
                   Using fixed bins ensures comparability across time windows.

    Returns:
        PSI as a non-negative float. 0.0 = identical distributions.

    Notes:
        - Zeros in expected or actual are clipped to 1e-4 to avoid log(0).
        - Values outside bin_edges are assigned to the first/last bin.
    """
    expected_counts, _ = np.histogram(expected, bins=bin_edges)
    actual_counts, _ = np.histogram(actual, bins=bin_edges)

    # Convert to proportions, avoid division by zero
    expected_prop = np.clip(expected_counts / (expected_counts.sum() + 1e-9), 1e-4, None)
    actual_prop = np.clip(actual_counts / (actual_counts.sum() + 1e-9), 1e-4, None)

    psi = float(np.sum((actual_prop - expected_prop) * np.log(actual_prop / expected_prop)))
    return psi


@dataclass
class FeatureDriftResult:
    """PSI result for a single feature."""

    feature: str
    psi: float
    status: str
    expected_distribution: list[float]
    actual_distribution: list[float]
    bin_edges: list[float]


@dataclass
class DriftReport:
    """Aggregated drift report for all monitored features."""

    computed_at: str
    n_recent_predictions: int
    overall_status: str
    features: list[FeatureDriftResult]
    recommendation: str


class DriftMonitor:
    """
    Loads training baseline and computes PSI for recent predictions.

    Baseline JSON format (generated by scripts/compute_baseline.py):
    {
        "mileage": {
            "bin_edges": [...],
            "expected_proportions": [...]
        },
        ...
    }
    """

    def __init__(self) -> None:
        self._baseline = self._load_baseline()
        logger.info(
            "DriftMonitor initialised for features: %s",
            list(self._baseline.keys()),
        )

    def compute_report(self, recent_records: list[dict]) -> dict:
        """
        Compute PSI for each monitored feature against the training baseline.

        Args:
            recent_records: List of DynamoDB audit log records, each containing
                            an 'input_features' dict with raw feature values.

        Returns:
            dict matching DriftReportResponse schema.
        """
        n = len(recent_records)
        if n < 50:
            logger.warning(
                "Only %d recent records available. PSI estimates unreliable below 50.", n
            )

        results: list[FeatureDriftResult] = []
        worst_psi = 0.0

        for feature in _MONITORED_FEATURES:
            baseline = self._baseline.get(feature)
            if baseline is None:
                logger.warning("No baseline for feature %r — skipping.", feature)
                continue

            bin_edges = np.array(baseline["bin_edges"])
            expected_prop = np.array(baseline["expected_proportions"])

            # Extract feature values from recent predictions
            actual_values = []
            for rec in recent_records:
                val = rec.get("input_features", {}).get(feature)
                if val is not None:
                    try:
                        actual_values.append(float(val))
                    except (TypeError, ValueError):
                        pass

            if len(actual_values) < 10:
                logger.warning("Feature %r: fewer than 10 actual values — skipping PSI.", feature)
                continue

            actual_arr = np.array(actual_values)
            actual_counts, _ = np.histogram(actual_arr, bins=bin_edges)
            actual_prop = np.clip(actual_counts / (actual_counts.sum() + 1e-9), 1e-4, None)

            expected_clipped = np.clip(expected_prop, 1e-4, None)
            psi = float(
                np.sum((actual_prop - expected_clipped) * np.log(actual_prop / expected_clipped))
            )

            status = self._psi_status(psi)
            worst_psi = max(worst_psi, psi)

            results.append(
                FeatureDriftResult(
                    feature=feature,
                    psi=round(psi, 4),
                    status=status,
                    expected_distribution=expected_prop.tolist(),
                    actual_distribution=actual_prop.tolist(),
                    bin_edges=bin_edges.tolist(),
                )
            )

        overall_status = self._psi_status(worst_psi)
        recommendation = self._recommendation(overall_status, worst_psi)

        report = DriftReport(
            computed_at=datetime.now(UTC).isoformat(),
            n_recent_predictions=n,
            overall_status=overall_status,
            features=results,
            recommendation=recommendation,
        )

        return {
            "computed_at": report.computed_at,
            "n_recent_predictions": report.n_recent_predictions,
            "overall_status": report.overall_status,
            "features": [asdict(f) for f in report.features],
            "recommendation": report.recommendation,
        }

    def publish_to_cloudwatch(self, report: dict) -> None:
        """
        Push PSI metrics to CloudWatch for alarming.

        Each monitored feature gets its own metric under namespace
        CarValuation. The drift alarm threshold is set at PSI > 0.2.
        """
        try:
            import boto3

            cw = boto3.client("cloudwatch", region_name=os.environ.get("AWS_REGION", "us-east-1"))
            metric_data = []
            for feature_report in report.get("features", []):
                metric_data.append(
                    {
                        "MetricName": f"PSI_{feature_report['feature']}",
                        "Value": feature_report["psi"],
                        "Unit": "None",
                        "Dimensions": [{"Name": "ModelVersion", "Value": "rand_forest_v1"}],
                    }
                )

            if metric_data:
                cw.put_metric_data(Namespace=_CLOUDWATCH_NAMESPACE, MetricData=metric_data)
                logger.info("Published %d PSI metrics to CloudWatch.", len(metric_data))

        except Exception:
            # Non-fatal: monitoring must not break serving
            logger.exception("Failed to publish drift metrics to CloudWatch.")

    # -----------------------------------------------------------------------
    # Private helpers
    # -----------------------------------------------------------------------

    @staticmethod
    def _psi_status(psi: float) -> str:
        if psi < _PSI_THRESHOLDS["stable"]:
            return "stable"
        elif psi < _PSI_THRESHOLDS["monitor"]:
            return "monitor"
        else:
            return "action_required"

    @staticmethod
    def _recommendation(status: str, worst_psi: float) -> str:
        if status == "stable":
            return "No action required. Model input distributions are stable."
        elif status == "monitor":
            return (
                f"Moderate drift detected (worst PSI={worst_psi:.3f}). "
                "Increase monitoring frequency. Check if recent data represents a seasonal shift."
            )
        else:
            return (
                f"Significant drift detected (worst PSI={worst_psi:.3f}). "
                "Investigate data pipeline for upstream changes. "
                "Consider retraining with recent data. "
                "Review model predictions for accuracy degradation."
            )

    @staticmethod
    def _load_baseline() -> dict:
        path_str = os.environ.get(_BASELINE_PATH_ENV, _BASELINE_PATH_DEFAULT)
        path = Path(path_str)
        if not path.exists():
            raise FileNotFoundError(
                f"Training baseline not found at {path.resolve()}. "
                "Run scripts/compute_baseline.py to generate it."
            )
        with open(path) as f:
            baseline = json.load(f)
        logger.info("Drift baseline loaded from %s.", path)
        return baseline
